build 3.7.5 on conda-forge
conda-forge/python-feedstock pull request #443
Opened 2021-01-26 17:28 UTC by wolfv

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2021-01-26 17:28 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2021-01-26 17:31 UTC, isuruf commented
Why?

2021-01-26 17:32 UTC, ocefpaf commented
> Why?

I'm not against it but also curious. Why?

2021-01-26 18:26 UTC, wolfv commented
Our friends at Robocorp (who are adopting conda-forge) need this specific version currently (and for some reason it's the missing one from conda-forge :)

Unfortunately there is some weird stuff happening with line endings and the newer conda-build.

2021-01-26 18:28 UTC, isuruf commented
That's not a reason. Please give a valid reason.

2021-01-26 18:34 UTC, wolfv commented
They have a pinning on this specific version of the Python interpreter that they are currently getting from the defaults channel. They want to further adopt conda-forge (lot's of robot-framework packages are already on conda-forge). But if they remove defaults, the current pinning isn't working anymore, so it would be great if conda-forge had a build of 3.7.5.

Basically, it's not possible for them to remove the pinning of 3.7.5 at this point (the pinning was introduced because of a bug in 3.7.6).

Since we advise on using either strict-channel-priority or not mixing defaults I think this is the way to go.

2021-01-26 18:39 UTC, isuruf commented
> Basically, it's not possible for them to remove the pinning of 3.7.5 at this point

Why?

2021-01-26 18:42 UTC, isuruf commented
Is this bug fixed in 3.7.7 or later? Do you have a link to the bug report?

2021-01-27 11:22 UTC, kariharju commented
Yeah so maybe good for me to chime on on the why questions on behalf of Robocorp.

We have at this point hundreds of user made robots running in production clouds and environments.
We are in the process of moving all these to use conda-forge and micromamba instead of anaconda defaults channel and miniconda. And on the tooling side we are moving on top of xeus-kernel. Both of these changes will free us from the locked python version, but...
Unfortunately when we started a year back we set the python version to 3.7.5 (our old kernel component also locked us to this version) so we had to put that in the templates and examples as well.. so it got pretty much everywhere.

So basically without 3.7.5 version being available in conda-forge we would have had to either keep using defaults channel or force the end-users to update all their setups. With 3.7.5 we can get the migrations rolling without forcing get more people to conda-forge.

2021-01-27 15:15 UTC, isuruf requested changes

2021-01-27 15:15 UTC, isuruf commented on recipe/patches/0016-Unvendor-openssl.patch
> -
Please keep this as it is

2021-01-27 15:15 UTC, isuruf commented on recipe/patches/0016-Unvendor-openssl.patch
> +       <Project>{cf7ac3d1-e2df-41d2-bea6-1e2556cdea26}</Project>
Please revert

2021-01-27 15:15 UTC, isuruf commented on recipe/patches/0016-Unvendor-openssl.patch
> +     <PyDebugExt Condition="'$(PyDebugExt)' == '' and $(Configuration) == 'Debug'">_d</PyDebugExt>
Please revert

2021-01-27 15:15 UTC, isuruf commented on recipe/patches/0016-Unvendor-openssl.patch
> +   </ItemGroup>
Please revert

2021-01-27 15:15 UTC, isuruf commented on recipe/patches/0017-Unvendor-sqlite3.patch
> -
Please revert

2021-01-27 15:15 UTC, isuruf commented on recipe/patches/0017-Unvendor-sqlite3.patch
> +     <!-- Suffix for versions/keys when building with test markers -->
Please revert

2021-01-27 15:16 UTC, isuruf commented
That makes more sense than what @wolfv did. Please add yourselves as maintainers here.

2021-01-27 18:59 UTC, wolfv commented
@isuruf the line ending behavior in conda-build has changed at some point, that's why the original patches don't apply cleanly anymore. Do you have some advice how to create clean patches?
I tried with `git apply old_patch.patch --ignore-whitespace` and then creating a new patch from that...

2021-01-27 19:38 UTC, isuruf commented
Okay then, please restore the metadata (Author, email, etc) and add yourselves as maintainers

2021-01-27 19:54 UTC, wolfv commented
Thanks, will do

2021-01-28 18:02 UTC, merged

2021-01-28 20:13 UTC, isuruf commented
@wolfv, can you send a PR to update this branch to 3.7.9 again?

2021-02-02 18:34 UTC, isuruf commented
@wolfv, ping on this

2021-02-02 19:12 UTC, wolfv commented
How do I do it in such a way that no new 3.7.9 packages are uploaded to CF?

2021-02-02 19:15 UTC, isuruf commented
That's fine. We also need to update the build number to something like 100 to avoid a conda solver issue.

2021-02-05 07:03 UTC, isuruf commented
Any updates?

2021-02-13 19:17 UTC, isuruf commented
Ping again

2021-02-13 19:18 UTC, wolfv commented
PR is open

2021-02-13 19:19 UTC, wolfv commented
https://github.com/conda-forge/python-feedstock/pull/446